### ISSUE TITLE
include librkdec-h264d.so

### ISSUE THREAD

**Issue by mac-l1** [rockchip-linux/libvdpau-rockchip#1]
Hi *, Jeffy Chen,

Not clear how to get librkdec-h264d.so file. Can the binary file be included? Or put the source code somewhere so that it is possible to build one.

Thx!

Cheers -- mac-l1

**Comment by pebauer68** [comment]
Did you have a look at e.g. ffmpeg, it has a binary called librk_codec.so inside, or is that a different lib ?
https://github.com/rockchip-linux/ffmpeg/tree/master/libvpu

**Comment by mac-l1** [comment]
not needed anymore as it is included in the repo
